baseurl = "https://dmitrijskass.netlify.com/"
languageCode = "en-us"
title = "Dmitrijs Kass"
theme = "hugo-lithium"
googleAnalytics = "UA-137778181-2"
disqusShortname = "https-dmitrijskass-netlify-com"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
	weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
	weight = 2
[params]
    description = "A website built through Hugo and blogdown."
    author = "Dmitrijs Kass"
	footer = "&copy; Dmitrijs Kass | [LinkedIn](https://www.linkedin.com/in/dmitrijs-kass-prm/) | [Github](https://github.com/dmitrijsk?tab=repositories) | [Twitter](https://twitter.com/DmitrijsKass)"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"
