baseurl: https://dmitrijskass.netlify.com/
languageCode: en-us
title: Dmitrijs Kass' blog
theme: hugo-lithium
googleAnalytics: 'UA-137778181-2'
disqusShortname: 'https-dmitrijskass-netlify-com'
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: About
      url: /about/
    - name: LinkedIn
      url: https://www.linkedin.com/in/dmitrijs-kass-prm/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0

